### ISSUE TITLE
Is this code still maintained?

### ISSUE THREAD

**Issue by fwuffyboi** [sphero-inc/sphero-sdk-raspberrypi-python#21]
The title. It seems as if Sphero have either abandoned or stopped working on this SDK. Personally I've had many issues trying to get it to work. Would just like to know if anyone else has recently gotten this to work. I'm using a raspberry pi 3B+ with debian lite. (I am only using ssh.)

**Comment by Jim-Konish** [comment]
Hi, we are still committed to maintaining this project, but you should expect only occasional updates due to development resource constraints.

As far as problems go, I see you opened an issue last year about UART communication issues.  I'll reply on that issue and close this one.
